public with sharing class ApexTransaction {
    public ApexTransaction() {
        
    }
/*
            In addition to the above you should have an Apex class which contains methods for the following:
            • Check if an account is overdrawn and change the status of the account accordingly.
            • Create a new transaction relating to the account.
            • Update the account based on all related transactions to show current balance.
        */
    public static void accountOverdrawnCheck(){
        
    }
}
